//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.296 版自动生成。
// 
#pragma warning disable 1591

namespace WorkFlow.UsersWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="usersBLLserviceSoap", Namespace="http://saron.workflowservice.org/")]
    public partial class usersBLLservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SysAdminLoginValidatorOperationCompleted;
        
        private SecurityContext securityContextValueField;
        
        private System.Threading.SendOrPostCallback ExistsLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSysAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteIdAndLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAdminByAppIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExistsLoginAndAppIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSysUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdminUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdminUpdatePassOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogicDeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetModelByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdminModelByAppIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserModelByLoginCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserModelByLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetModelByAppIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUsersListOfAppOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public usersBLLservice() {
            this.Url = global::WorkFlow.Properties.Settings.Default.WorkFlow_UsersWebService_usersBLLservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SecurityContext SecurityContextValue {
            get {
                return this.securityContextValueField;
            }
            set {
                this.securityContextValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SysAdminLoginValidatorCompletedEventHandler SysAdminLoginValidatorCompleted;
        
        /// <remarks/>
        public event ExistsLoginCompletedEventHandler ExistsLoginCompleted;
        
        /// <remarks/>
        public event AddSysAdminCompletedEventHandler AddSysAdminCompleted;
        
        /// <remarks/>
        public event DeleteIdAndLoginCompletedEventHandler DeleteIdAndLoginCompleted;
        
        /// <remarks/>
        public event DeleteAdminByAppIDCompletedEventHandler DeleteAdminByAppIDCompleted;
        
        /// <remarks/>
        public event ExistsLoginAndAppIDCompletedEventHandler ExistsLoginAndAppIDCompleted;
        
        /// <remarks/>
        public event AddSysUserCompletedEventHandler AddSysUserCompleted;
        
        /// <remarks/>
        public event AdminUpdateCompletedEventHandler AdminUpdateCompleted;
        
        /// <remarks/>
        public event AdminUpdatePassCompletedEventHandler AdminUpdatePassCompleted;
        
        /// <remarks/>
        public event LogicDeleteCompletedEventHandler LogicDeleteCompleted;
        
        /// <remarks/>
        public event GetModelByIDCompletedEventHandler GetModelByIDCompleted;
        
        /// <remarks/>
        public event GetAdminModelByAppIDCompletedEventHandler GetAdminModelByAppIDCompleted;
        
        /// <remarks/>
        public event GetUserModelByLoginCKCompletedEventHandler GetUserModelByLoginCKCompleted;
        
        /// <remarks/>
        public event GetUserModelByLoginCompletedEventHandler GetUserModelByLoginCompleted;
        
        /// <remarks/>
        public event GetModelByAppIDCompletedEventHandler GetModelByAppIDCompleted;
        
        /// <remarks/>
        public event GetAllUsersListOfAppCompletedEventHandler GetAllUsersListOfAppCompleted;
        
        /// <remarks/>
        public event ModifyPasswordCompletedEventHandler ModifyPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/SysAdminLoginValidator", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SysAdminLoginValidator(string login, string password, out string msg) {
            object[] results = this.Invoke("SysAdminLoginValidator", new object[] {
                        login,
                        password});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SysAdminLoginValidatorAsync(string login, string password) {
            this.SysAdminLoginValidatorAsync(login, password, null);
        }
        
        /// <remarks/>
        public void SysAdminLoginValidatorAsync(string login, string password, object userState) {
            if ((this.SysAdminLoginValidatorOperationCompleted == null)) {
                this.SysAdminLoginValidatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSysAdminLoginValidatorOperationCompleted);
            }
            this.InvokeAsync("SysAdminLoginValidator", new object[] {
                        login,
                        password}, this.SysAdminLoginValidatorOperationCompleted, userState);
        }
        
        private void OnSysAdminLoginValidatorOperationCompleted(object arg) {
            if ((this.SysAdminLoginValidatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SysAdminLoginValidatorCompleted(this, new SysAdminLoginValidatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/ExistsLogin", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExistsLogin(string login, out string msg) {
            object[] results = this.Invoke("ExistsLogin", new object[] {
                        login});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExistsLoginAsync(string login) {
            this.ExistsLoginAsync(login, null);
        }
        
        /// <remarks/>
        public void ExistsLoginAsync(string login, object userState) {
            if ((this.ExistsLoginOperationCompleted == null)) {
                this.ExistsLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExistsLoginOperationCompleted);
            }
            this.InvokeAsync("ExistsLogin", new object[] {
                        login}, this.ExistsLoginOperationCompleted, userState);
        }
        
        private void OnExistsLoginOperationCompleted(object arg) {
            if ((this.ExistsLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExistsLoginCompleted(this, new ExistsLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/AddSysAdmin", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddSysAdmin(usersModel model, out string msg) {
            object[] results = this.Invoke("AddSysAdmin", new object[] {
                        model});
            msg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddSysAdminAsync(usersModel model) {
            this.AddSysAdminAsync(model, null);
        }
        
        /// <remarks/>
        public void AddSysAdminAsync(usersModel model, object userState) {
            if ((this.AddSysAdminOperationCompleted == null)) {
                this.AddSysAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSysAdminOperationCompleted);
            }
            this.InvokeAsync("AddSysAdmin", new object[] {
                        model}, this.AddSysAdminOperationCompleted, userState);
        }
        
        private void OnAddSysAdminOperationCompleted(object arg) {
            if ((this.AddSysAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSysAdminCompleted(this, new AddSysAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/DeleteIdAndLogin", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteIdAndLogin(int id, string login) {
            object[] results = this.Invoke("DeleteIdAndLogin", new object[] {
                        id,
                        login});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteIdAndLoginAsync(int id, string login) {
            this.DeleteIdAndLoginAsync(id, login, null);
        }
        
        /// <remarks/>
        public void DeleteIdAndLoginAsync(int id, string login, object userState) {
            if ((this.DeleteIdAndLoginOperationCompleted == null)) {
                this.DeleteIdAndLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteIdAndLoginOperationCompleted);
            }
            this.InvokeAsync("DeleteIdAndLogin", new object[] {
                        id,
                        login}, this.DeleteIdAndLoginOperationCompleted, userState);
        }
        
        private void OnDeleteIdAndLoginOperationCompleted(object arg) {
            if ((this.DeleteIdAndLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteIdAndLoginCompleted(this, new DeleteIdAndLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/DeleteAdminByAppID", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteAdminByAppID(int appID, out string msg) {
            object[] results = this.Invoke("DeleteAdminByAppID", new object[] {
                        appID});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAdminByAppIDAsync(int appID) {
            this.DeleteAdminByAppIDAsync(appID, null);
        }
        
        /// <remarks/>
        public void DeleteAdminByAppIDAsync(int appID, object userState) {
            if ((this.DeleteAdminByAppIDOperationCompleted == null)) {
                this.DeleteAdminByAppIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAdminByAppIDOperationCompleted);
            }
            this.InvokeAsync("DeleteAdminByAppID", new object[] {
                        appID}, this.DeleteAdminByAppIDOperationCompleted, userState);
        }
        
        private void OnDeleteAdminByAppIDOperationCompleted(object arg) {
            if ((this.DeleteAdminByAppIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAdminByAppIDCompleted(this, new DeleteAdminByAppIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/ExistsLoginAndAppID", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExistsLoginAndAppID(string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> appId, out string msg) {
            object[] results = this.Invoke("ExistsLoginAndAppID", new object[] {
                        login,
                        appId});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExistsLoginAndAppIDAsync(string login, System.Nullable<int> appId) {
            this.ExistsLoginAndAppIDAsync(login, appId, null);
        }
        
        /// <remarks/>
        public void ExistsLoginAndAppIDAsync(string login, System.Nullable<int> appId, object userState) {
            if ((this.ExistsLoginAndAppIDOperationCompleted == null)) {
                this.ExistsLoginAndAppIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExistsLoginAndAppIDOperationCompleted);
            }
            this.InvokeAsync("ExistsLoginAndAppID", new object[] {
                        login,
                        appId}, this.ExistsLoginAndAppIDOperationCompleted, userState);
        }
        
        private void OnExistsLoginAndAppIDOperationCompleted(object arg) {
            if ((this.ExistsLoginAndAppIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExistsLoginAndAppIDCompleted(this, new ExistsLoginAndAppIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/AddSysUser", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddSysUser(usersModel model, out string msg) {
            object[] results = this.Invoke("AddSysUser", new object[] {
                        model});
            msg = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddSysUserAsync(usersModel model) {
            this.AddSysUserAsync(model, null);
        }
        
        /// <remarks/>
        public void AddSysUserAsync(usersModel model, object userState) {
            if ((this.AddSysUserOperationCompleted == null)) {
                this.AddSysUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSysUserOperationCompleted);
            }
            this.InvokeAsync("AddSysUser", new object[] {
                        model}, this.AddSysUserOperationCompleted, userState);
        }
        
        private void OnAddSysUserOperationCompleted(object arg) {
            if ((this.AddSysUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSysUserCompleted(this, new AddSysUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/AdminUpdate", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AdminUpdate(usersModel model, out string msg) {
            object[] results = this.Invoke("AdminUpdate", new object[] {
                        model});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AdminUpdateAsync(usersModel model) {
            this.AdminUpdateAsync(model, null);
        }
        
        /// <remarks/>
        public void AdminUpdateAsync(usersModel model, object userState) {
            if ((this.AdminUpdateOperationCompleted == null)) {
                this.AdminUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdminUpdateOperationCompleted);
            }
            this.InvokeAsync("AdminUpdate", new object[] {
                        model}, this.AdminUpdateOperationCompleted, userState);
        }
        
        private void OnAdminUpdateOperationCompleted(object arg) {
            if ((this.AdminUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdminUpdateCompleted(this, new AdminUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/AdminUpdatePass", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AdminUpdatePass(usersModel model, out string msg) {
            object[] results = this.Invoke("AdminUpdatePass", new object[] {
                        model});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AdminUpdatePassAsync(usersModel model) {
            this.AdminUpdatePassAsync(model, null);
        }
        
        /// <remarks/>
        public void AdminUpdatePassAsync(usersModel model, object userState) {
            if ((this.AdminUpdatePassOperationCompleted == null)) {
                this.AdminUpdatePassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdminUpdatePassOperationCompleted);
            }
            this.InvokeAsync("AdminUpdatePass", new object[] {
                        model}, this.AdminUpdatePassOperationCompleted, userState);
        }
        
        private void OnAdminUpdatePassOperationCompleted(object arg) {
            if ((this.AdminUpdatePassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdminUpdatePassCompleted(this, new AdminUpdatePassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/LogicDelete", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LogicDelete(int id, out string msg) {
            object[] results = this.Invoke("LogicDelete", new object[] {
                        id});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LogicDeleteAsync(int id) {
            this.LogicDeleteAsync(id, null);
        }
        
        /// <remarks/>
        public void LogicDeleteAsync(int id, object userState) {
            if ((this.LogicDeleteOperationCompleted == null)) {
                this.LogicDeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogicDeleteOperationCompleted);
            }
            this.InvokeAsync("LogicDelete", new object[] {
                        id}, this.LogicDeleteOperationCompleted, userState);
        }
        
        private void OnLogicDeleteOperationCompleted(object arg) {
            if ((this.LogicDeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogicDeleteCompleted(this, new LogicDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/GetModelByID", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usersModel GetModelByID(int id, out string msg) {
            object[] results = this.Invoke("GetModelByID", new object[] {
                        id});
            msg = ((string)(results[1]));
            return ((usersModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetModelByIDAsync(int id) {
            this.GetModelByIDAsync(id, null);
        }
        
        /// <remarks/>
        public void GetModelByIDAsync(int id, object userState) {
            if ((this.GetModelByIDOperationCompleted == null)) {
                this.GetModelByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModelByIDOperationCompleted);
            }
            this.InvokeAsync("GetModelByID", new object[] {
                        id}, this.GetModelByIDOperationCompleted, userState);
        }
        
        private void OnGetModelByIDOperationCompleted(object arg) {
            if ((this.GetModelByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModelByIDCompleted(this, new GetModelByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/GetAdminModelByAppID", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usersModel GetAdminModelByAppID(int appid, out string msg) {
            object[] results = this.Invoke("GetAdminModelByAppID", new object[] {
                        appid});
            msg = ((string)(results[1]));
            return ((usersModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdminModelByAppIDAsync(int appid) {
            this.GetAdminModelByAppIDAsync(appid, null);
        }
        
        /// <remarks/>
        public void GetAdminModelByAppIDAsync(int appid, object userState) {
            if ((this.GetAdminModelByAppIDOperationCompleted == null)) {
                this.GetAdminModelByAppIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdminModelByAppIDOperationCompleted);
            }
            this.InvokeAsync("GetAdminModelByAppID", new object[] {
                        appid}, this.GetAdminModelByAppIDOperationCompleted, userState);
        }
        
        private void OnGetAdminModelByAppIDOperationCompleted(object arg) {
            if ((this.GetAdminModelByAppIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdminModelByAppIDCompleted(this, new GetAdminModelByAppIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/GetUserModelByLoginCK", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usersModel GetUserModelByLoginCK(string login, out string msg) {
            object[] results = this.Invoke("GetUserModelByLoginCK", new object[] {
                        login});
            msg = ((string)(results[1]));
            return ((usersModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserModelByLoginCKAsync(string login) {
            this.GetUserModelByLoginCKAsync(login, null);
        }
        
        /// <remarks/>
        public void GetUserModelByLoginCKAsync(string login, object userState) {
            if ((this.GetUserModelByLoginCKOperationCompleted == null)) {
                this.GetUserModelByLoginCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserModelByLoginCKOperationCompleted);
            }
            this.InvokeAsync("GetUserModelByLoginCK", new object[] {
                        login}, this.GetUserModelByLoginCKOperationCompleted, userState);
        }
        
        private void OnGetUserModelByLoginCKOperationCompleted(object arg) {
            if ((this.GetUserModelByLoginCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserModelByLoginCKCompleted(this, new GetUserModelByLoginCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/GetUserModelByLogin", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usersModel GetUserModelByLogin(string login, out string msg) {
            object[] results = this.Invoke("GetUserModelByLogin", new object[] {
                        login});
            msg = ((string)(results[1]));
            return ((usersModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserModelByLoginAsync(string login) {
            this.GetUserModelByLoginAsync(login, null);
        }
        
        /// <remarks/>
        public void GetUserModelByLoginAsync(string login, object userState) {
            if ((this.GetUserModelByLoginOperationCompleted == null)) {
                this.GetUserModelByLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserModelByLoginOperationCompleted);
            }
            this.InvokeAsync("GetUserModelByLogin", new object[] {
                        login}, this.GetUserModelByLoginOperationCompleted, userState);
        }
        
        private void OnGetUserModelByLoginOperationCompleted(object arg) {
            if ((this.GetUserModelByLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserModelByLoginCompleted(this, new GetUserModelByLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/GetModelByAppID", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public usersModel GetModelByAppID(int appID, out string msg) {
            object[] results = this.Invoke("GetModelByAppID", new object[] {
                        appID});
            msg = ((string)(results[1]));
            return ((usersModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetModelByAppIDAsync(int appID) {
            this.GetModelByAppIDAsync(appID, null);
        }
        
        /// <remarks/>
        public void GetModelByAppIDAsync(int appID, object userState) {
            if ((this.GetModelByAppIDOperationCompleted == null)) {
                this.GetModelByAppIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModelByAppIDOperationCompleted);
            }
            this.InvokeAsync("GetModelByAppID", new object[] {
                        appID}, this.GetModelByAppIDOperationCompleted, userState);
        }
        
        private void OnGetModelByAppIDOperationCompleted(object arg) {
            if ((this.GetModelByAppIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModelByAppIDCompleted(this, new GetModelByAppIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/GetAllUsersListOfApp", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllUsersListOfApp(int appID, out string msg) {
            object[] results = this.Invoke("GetAllUsersListOfApp", new object[] {
                        appID});
            msg = ((string)(results[1]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUsersListOfAppAsync(int appID) {
            this.GetAllUsersListOfAppAsync(appID, null);
        }
        
        /// <remarks/>
        public void GetAllUsersListOfAppAsync(int appID, object userState) {
            if ((this.GetAllUsersListOfAppOperationCompleted == null)) {
                this.GetAllUsersListOfAppOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUsersListOfAppOperationCompleted);
            }
            this.InvokeAsync("GetAllUsersListOfApp", new object[] {
                        appID}, this.GetAllUsersListOfAppOperationCompleted, userState);
        }
        
        private void OnGetAllUsersListOfAppOperationCompleted(object arg) {
            if ((this.GetAllUsersListOfAppCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUsersListOfAppCompleted(this, new GetAllUsersListOfAppCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saron.workflowservice.org/ModifyPassword", RequestNamespace="http://saron.workflowservice.org/", ResponseNamespace="http://saron.workflowservice.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ModifyPassword(string login, string password, out string msg) {
            object[] results = this.Invoke("ModifyPassword", new object[] {
                        login,
                        password});
            msg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyPasswordAsync(string login, string password) {
            this.ModifyPasswordAsync(login, password, null);
        }
        
        /// <remarks/>
        public void ModifyPasswordAsync(string login, string password, object userState) {
            if ((this.ModifyPasswordOperationCompleted == null)) {
                this.ModifyPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyPasswordOperationCompleted);
            }
            this.InvokeAsync("ModifyPassword", new object[] {
                        login,
                        password}, this.ModifyPasswordOperationCompleted, userState);
        }
        
        private void OnModifyPasswordOperationCompleted(object arg) {
            if ((this.ModifyPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyPasswordCompleted(this, new ModifyPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://saron.workflowservice.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://saron.workflowservice.org/", IsNullable=false)]
    public partial class SecurityContext : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passWordField;
        
        private int appIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        public int AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://saron.workflowservice.org/")]
    public partial class usersModel {
        
        private int idField;
        
        private string loginField;
        
        private string passwordField;
        
        private string nameField;
        
        private string employee_noField;
        
        private string mobile_phoneField;
        
        private string mailField;
        
        private string remarkField;
        
        private bool adminField;
        
        private bool invalidField;
        
        private bool deletedField;
        
        private System.DateTime created_atField;
        
        private int created_byField;
        
        private string created_ipField;
        
        private System.Nullable<System.DateTime> updated_atField;
        
        private System.Nullable<int> updated_byField;
        
        private string updated_ipField;
        
        private System.Nullable<int> app_idField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string employee_no {
            get {
                return this.employee_noField;
            }
            set {
                this.employee_noField = value;
            }
        }
        
        /// <remarks/>
        public string mobile_phone {
            get {
                return this.mobile_phoneField;
            }
            set {
                this.mobile_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public bool admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
            }
        }
        
        /// <remarks/>
        public bool invalid {
            get {
                return this.invalidField;
            }
            set {
                this.invalidField = value;
            }
        }
        
        /// <remarks/>
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime created_at {
            get {
                return this.created_atField;
            }
            set {
                this.created_atField = value;
            }
        }
        
        /// <remarks/>
        public int created_by {
            get {
                return this.created_byField;
            }
            set {
                this.created_byField = value;
            }
        }
        
        /// <remarks/>
        public string created_ip {
            get {
                return this.created_ipField;
            }
            set {
                this.created_ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> updated_at {
            get {
                return this.updated_atField;
            }
            set {
                this.updated_atField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> updated_by {
            get {
                return this.updated_byField;
            }
            set {
                this.updated_byField = value;
            }
        }
        
        /// <remarks/>
        public string updated_ip {
            get {
                return this.updated_ipField;
            }
            set {
                this.updated_ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> app_id {
            get {
                return this.app_idField;
            }
            set {
                this.app_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SysAdminLoginValidatorCompletedEventHandler(object sender, SysAdminLoginValidatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SysAdminLoginValidatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SysAdminLoginValidatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ExistsLoginCompletedEventHandler(object sender, ExistsLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExistsLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExistsLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddSysAdminCompletedEventHandler(object sender, AddSysAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSysAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSysAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteIdAndLoginCompletedEventHandler(object sender, DeleteIdAndLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteIdAndLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteIdAndLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteAdminByAppIDCompletedEventHandler(object sender, DeleteAdminByAppIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAdminByAppIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAdminByAppIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ExistsLoginAndAppIDCompletedEventHandler(object sender, ExistsLoginAndAppIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExistsLoginAndAppIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExistsLoginAndAppIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddSysUserCompletedEventHandler(object sender, AddSysUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSysUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSysUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AdminUpdateCompletedEventHandler(object sender, AdminUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdminUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdminUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AdminUpdatePassCompletedEventHandler(object sender, AdminUpdatePassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdminUpdatePassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdminUpdatePassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LogicDeleteCompletedEventHandler(object sender, LogicDeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogicDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogicDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetModelByIDCompletedEventHandler(object sender, GetModelByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModelByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModelByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usersModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usersModel)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAdminModelByAppIDCompletedEventHandler(object sender, GetAdminModelByAppIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdminModelByAppIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdminModelByAppIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usersModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usersModel)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserModelByLoginCKCompletedEventHandler(object sender, GetUserModelByLoginCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserModelByLoginCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserModelByLoginCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usersModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usersModel)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserModelByLoginCompletedEventHandler(object sender, GetUserModelByLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserModelByLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserModelByLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usersModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usersModel)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetModelByAppIDCompletedEventHandler(object sender, GetModelByAppIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModelByAppIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModelByAppIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public usersModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((usersModel)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllUsersListOfAppCompletedEventHandler(object sender, GetAllUsersListOfAppCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUsersListOfAppCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUsersListOfAppCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModifyPasswordCompletedEventHandler(object sender, ModifyPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591